config/routes.rb
Rails.application.routes.draw do
  resources :rinks
  devise_for :users
  root 'games#index'
  resources :users
  resources :game_types, :leagues, :play_types, :plays, :reviews, :teams, :user_types, :venues

  resources :games do
    resources :plays
  end

  resources :plays do
    resources :reviews
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :game_type
  belongs_to :rink
  belongs_to :venue
  belongs_to :team_one, class_name: 'Team'
  belongs_to :team_two, class_name: 'Team'
  has_many :plays

  accepts_nested_attributes_for :plays

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  def plays_for_form
    collection = plays.where(game_id: id)
    collection.any? ? collection : plays.build
  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
  has_many :games
  has_many :teams
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams
  has_many :venues
  belongs_to :game_type
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :play_type
  has_many :reviews
  belongs_to :game
end

app/models/play_type.rb
class PlayType < ApplicationRecord
  has_many :plays
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :play
  belongs_to :user

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
end

app/models/rink.rb
class Rink < ApplicationRecord
  has_many :games
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_one_games, :class_name => 'Game', :foreign_key => 'team_one_id'
  has_many :team_two_games, :class_name => 'Game', :foreign_key => 'team_two_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  # belongs_to :user_type
end

app/models/user_type.rb
class UserType < ApplicationRecord
  has_many :users
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :games
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
end

app/controllers/rinks_controller.rb
class RinksController < ApplicationController
  before_action :set_rink, only: [:show, :edit, :update, :destroy]

  # GET /rinks
  # GET /rinks.json
  def index
    @rinks = Rink.all
  end

  # GET /rinks/1
  # GET /rinks/1.json
  def show
  end

  # GET /rinks/new
  def new
    @rink = Rink.new
  end

  # GET /rinks/1/edit
  def edit
  end

  # POST /rinks
  # POST /rinks.json
  def create
    @rink = Rink.new(rink_params)

    respond_to do |format|
      if @rink.save
        format.html { redirect_to @rink, notice: 'Rink was successfully created.' }
        format.json { render :show, status: :created, location: @rink }
      else
        format.html { render :new }
        format.json { render json: @rink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rinks/1
  # PATCH/PUT /rinks/1.json
  def update
    respond_to do |format|
      if @rink.update(rink_params)
        format.html { redirect_to @rink, notice: 'Rink was successfully updated.' }
        format.json { render :show, status: :ok, location: @rink }
      else
        format.html { render :edit }
        format.json { render json: @rink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rinks/1
  # DELETE /rinks/1.json
  def destroy
    @rink.destroy
    respond_to do |format|
      format.html { redirect_to rinks_url, notice: 'Rink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rink
      @rink = Rink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rink_params
      params.require(:rink).permit(:name, :note)
    end
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/play_types_helper.rb
module PlayTypesHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rinks_helper.rb
module RinksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/rinks/_form.html.erb
<%= simple_form_for(@rink) do |f| %>
  <% if rink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rink.errors.count, "error") %> prohibited this rink from being saved:</h2>

      <ul>
        <% rink.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :note %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rinks/edit.html.erb
<h1>Editing Rink</h1>

<%= render 'form', rink: @rink %>

<%= link_to 'Show', @rink %> |
<%= link_to 'Back', rinks_path %>

app/views/rinks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rinks</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rinks.each do |rink| %>
      <tr>
        <td><%= rink.name %></td>
        <td><%= rink.note %></td>
        <td><%= link_to 'Show', rink %></td>
        <td><%= link_to 'Edit', edit_rink_path(rink) %></td>
        <td><%= link_to 'Destroy', rink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rink', new_rink_path %>

app/views/rinks/new.html.erb
<h1>New Rink</h1>

<%= render 'form', rink: @rink %>

<%= link_to 'Back', rinks_path %>

app/views/rinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rink.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @rink.note %>
</p>

<%= link_to 'Edit', edit_rink_path(@rink) %> |
<%= link_to 'Back', rinks_path %>