config/routes.rb
Rails.application.routes.draw do
  resources :rinks
  devise_for :users
  root 'games#index'
  resources :users
  resources :game_types, :leagues, :play_types, :plays, :reviews, :teams, :user_types, :venues

  resources :games do
    resources :plays
  end

  resources :plays do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :game_type
  belongs_to :rink
  belongs_to :venue
  belongs_to :team_one, class_name: 'Team'
  belongs_to :team_two, class_name: 'Team'
  has_many :plays

  accepts_nested_attributes_for :plays

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  def plays_for_form
    collection = plays.where(game_id: id)
    collection.any? ? collection : plays.build
  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
  has_many :games
  has_many :teams
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams
  has_many :venues
  belongs_to :game_type
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :play_type
  has_many :reviews
  belongs_to :game
end

app/models/play_type.rb
class PlayType < ApplicationRecord
  has_many :plays
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :play
  belongs_to :user

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
end

app/models/rink.rb
class Rink < ApplicationRecord
  has_many :games
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_one_games, :class_name => 'Game', :foreign_key => 'team_one_id'
  has_many :team_two_games, :class_name => 'Game', :foreign_key => 'team_two_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  # belongs_to :user_type
end

app/models/user_type.rb
class UserType < ApplicationRecord
  has_many :users
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :games
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]

  # GET /plays
  # GET /plays.json
  def index
    @plays = Play.all
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
  end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new(play_params)
    @play.name = PlayType.find(play_params[:play_type_id]).name

    respond_to do |format|
      if @play.save
        format.html { redirect_to game_path(@play.game_id), notice: 'Play was successfully created.' }
        format.json { render :show, status: :created, location: @play }
      else
        format.html { render :new }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { render :show, status: :ok, location: @play }
      else
        format.html { render :edit }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @game = Game.find(params[:game_id])
    @play = @game.plays.find(params[:id])
    @play.destroy


    respond_to do |format|
      format.html { redirect_to game_path(@game), notice: 'Play was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
      params.require(:play).permit(:name, :game_id, :play_type_id)
    end
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/play_types_helper.rb
module PlayTypesHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rinks_helper.rb
module RinksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/plays/_form.html.erb
<%= form_with(model: play, local: true) do |form| %>
  <% if play.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(play.errors.count, "error") %> prohibited this play from being saved:</h2>

      <ul>
      <% play.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :play_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plays/edit.html.erb
<h1>Editing Play</h1>

<%= render 'form', play: @play %>

<%= link_to 'Show', @play %> |
<%= link_to 'Back', plays_path %>

app/views/plays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plays</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plays.each do |play| %>
      <tr>
        <td><%= play.name %></td>
        <td><%= link_to 'Show', play %></td>
        <td><%= link_to 'Edit', edit_play_path(play) %></td>
        <td><%= link_to 'Destroy', play, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Play', new_play_path %>

app/views/plays/new.html.erb
<div class="container">
  <div class="col-sm-6">
    <h1>New Play</h1>
    <%= render 'form', play: @play %>
    <%= link_to 'Back', plays_path %>
  </div>
</div>

app/views/plays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<h2>Play: <%= "#{@play.name} @ #{@play.created_at.strftime('%I:%M:%S %p')}" %></h2>
</p>

<h2>Reviews</h2>
<% @play.reviews.each do |review| %>
  <p>
  <div class="row">
    <div class="col-4">
      <%= link_to "Review @ #{review.created_at.strftime('%I:%M:%S %p')} | User says: #{review.agree}", review_path(review), class: 'btn btn-outline-primary btn-block' %>
    </div>
    <div class="col-1">
      <%= link_to 'Delete', [review.play, review], method: :delete, class: 'btn btn-outline-danger btn-block' %>
    </div>
  </div>
  </p>
<% end %>

<h3>Add a review:</h3>
<%= form_with(model: [ @play, @play.reviews.build ], local: true) do |form| %>
  <p>
    <%= label :agree, "Agree", value: true %>
    <%= form.radio_button :agree, true, checked: true, value: true %>
    <%= label :disagree, "Disagree", value: false %>
    <%= form.radio_button :agree, false, value: false %>
  </p>


    <%= label :confidence, "Confidence", value: true %>

  <p>
    <%= label :confidence, "High", value: true %>
    <%= form.radio_button :confidence, 10, checked: true, value: 10 %>&nbsp;

    <%= label :confidence, "Medium", value: true %>
    <%= form.radio_button :confidence, 9, checked: true, value: 9 %>

    <%= label :confidence, "Low", value: true %>
    <%= form.radio_button :confidence, 9, checked: true, value: 9 %>
  </p>

  <p>
    <%# form.label 'Review Type' %>

    <%# form.select :play_type_id, PlayType.all.collect {|p| [ p.name, p.id ] } %>
    <% form.hidden_field :play_id, value: @play.id %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>



<%= link_to 'Edit', edit_play_path(@play) %> |
<%= link_to 'Back', plays_path %>