config/routes.rb
Rails.application.routes.draw do
  resources :rinks
  devise_for :users
  root 'games#index'
  resources :users
  resources :game_types, :leagues, :play_types, :plays, :reviews, :teams, :user_types, :venues

  resources :games do
    resources :plays
  end

  resources :plays do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :game_type
  belongs_to :rink
  belongs_to :venue
  belongs_to :team_one, class_name: 'Team'
  belongs_to :team_two, class_name: 'Team'
  has_many :plays

  accepts_nested_attributes_for :plays

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  def plays_for_form
    collection = plays.where(game_id: id)
    collection.any? ? collection : plays.build
  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
  has_many :games
  has_many :teams
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams
  has_many :venues
  belongs_to :game_type
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :play_type
  has_many :reviews
  belongs_to :game
end

app/models/play_type.rb
class PlayType < ApplicationRecord
  has_many :plays
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :play
  belongs_to :user

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
end

app/models/rink.rb
class Rink < ApplicationRecord
  has_many :games
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_one_games, :class_name => 'Game', :foreign_key => 'team_one_id'
  has_many :team_two_games, :class_name => 'Game', :foreign_key => 'team_two_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  # belongs_to :user_type
end

app/models/user_type.rb
class UserType < ApplicationRecord
  has_many :users
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :games
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.name = game_name(@game)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def tighten(input)
      input.split.map(&:capitalize).join(' ').gsub(/\s+/, "")
    end

    def game_name(game)
      "#{tighten(game.team_one.name)} vs. #{tighten(game.team_two.name)} @ #{tighten(game.venue.name)}-#{game.game_time.strftime('[%m/%d/%Y-%l:%M %p]').to_s}"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :game_type_id, :venue_id, :team_one_id, :team_two_id, :rink_id, :game_time)
    end
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/play_types_helper.rb
module PlayTypesHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rinks_helper.rb
module RinksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for @game do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%# form.label :team_one %>
    <%= form.input :team_one_id, collection: Team.all %>
  </div>
  <div class="field">
    <%# form.label :team_two %>
    <%= form.input :team_two_id, collection: Team.all %>
  </div>
  <div class="field">
    <%# form.label :venue %>
    <%= form.input :venue_id, collection: Venue.all %>
  </div>
  <div class="field">
    <%# form.label :game_type %>
    <%= form.input :game_type_id, collection: GameType.all %>
  </div>
  <div class="field">
    <%# form.label :game_type %>
    <%= form.input :rink_id, collection: Rink.all, label: 'Arena' %>
  </div>
  <div class="field" style="width: 500px">
    <%# form.label :game_type %>
    <%= form.input :game_time %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_show_game.html.erb
<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>
<p>
  <strong>Team 1:</strong>
  <%= @game.team_one.name %>
</p>
<p>
  <strong>Team 2:</strong>
  <%= @game.team_two.name %>
</p>
<p>
  <strong>Type:</strong>
  <%= @game.game_type.name %>
</p>
<p>
  <strong>Venue:</strong>
  <%= @game.venue.name %>
</p>
<p>
  <strong>Arena:</strong>
  <%= @game.rink.name %>
</p>
<p>
  <strong>Time:</strong>
  <%= @game.game_time.strftime('%A, %d %b %Y %l:%M %p') %>
</p>

app/views/games/edit.html.erb
<div class="col-sm-4">
  <h1>Editing Game</h1>
  <%= render 'form', game: @game %><br>
  <%= link_to 'Show', @game %> |
  <%= link_to 'Back', games_path %>
</div>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

  <h1>Games</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= link_to game&.name, game_path(game) %></td>
          <td><%= link_to '', edit_game_path(game), class: 'fa fa-edit fa-2x' %></td>
          <td><%= link_to '', game, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash fa-2x' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<div class="col-sm-4">
  <h1>New Game</h1>
  <%= render 'form', game: @game %><br>
  <%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'show_game' %>

<h2>Plays</h2>
<% @game.plays.each do |play| %>
  <p>
    <div class="row">
      <div class="col-4">
        <%= link_to "#{play.name} - #{play.created_at.strftime('%I:%M:%S %p')}", play_path(play), class: 'btn btn-outline-primary btn-block' %>
      </div>
      <div class="col-1">
        <%= link_to 'Delete', [play.game, play], method: :delete, class: 'btn btn-outline-danger btn-block' %>
      </div>
    </div>
  </p>
<% end %>

<h3>Add a play:</h3>
<%= form_with(model: [ @game, @game.plays.build ], local: true) do |form| %>
  <p>
    <%= form.label 'Play Type' %>
    <%= form.select :play_type_id, PlayType.all.collect {|p| [ p.name, p.id ] } %>
    <%= form.hidden_field :game_id, value: @game.id %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>