config/routes.rb
Rails.application.routes.draw do
  resources :rinks
  devise_for :users
  root 'games#index'
  resources :users
  resources :game_types, :leagues, :play_types, :plays, :reviews, :teams, :user_types, :venues

  resources :games do
    resources :plays
  end

  resources :plays do
    resources :reviews
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :game_type
  belongs_to :rink
  belongs_to :venue
  belongs_to :team_one, class_name: 'Team'
  belongs_to :team_two, class_name: 'Team'
  has_many :plays

  accepts_nested_attributes_for :plays

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  def plays_for_form
    collection = plays.where(game_id: id)
    collection.any? ? collection : plays.build
  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
  has_many :games
  has_many :teams
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams
  has_many :venues
  belongs_to :game_type
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :play_type
  has_many :reviews
  belongs_to :game
end

app/models/play_type.rb
class PlayType < ApplicationRecord
  has_many :plays
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :play
  belongs_to :user

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
end

app/models/rink.rb
class Rink < ApplicationRecord
  has_many :games
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_one_games, :class_name => 'Game', :foreign_key => 'team_one_id'
  has_many :team_two_games, :class_name => 'Game', :foreign_key => 'team_two_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  # belongs_to :user_type
end

app/models/user_type.rb
class UserType < ApplicationRecord
  has_many :users
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :games
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rinks_helper.rb
module RinksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportsVote</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



    <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right"
                type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= venues_path %>">Venues</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= leagues_path %>">Leagues</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= teams_path %>">Teams</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= games_path %>">Games</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= game_types_path %>">Game Types</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= play_types_path %>">Play Types</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= reviews_path %>">Reviews</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= rinks_path %>">Rinks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= users_path %>">< Admin Users ></a>
            </li>
          </ul>
          <% if user_signed_in? %>
            <ul class="navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to("Profile", edit_user_registration_path) %></li>
                  <li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
                </ul>
              </li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to('Login', new_user_session_path) %></li>
            </ul>
          <% end %>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>